### PR TITLE
Issue143

### PR DESCRIPTION
**Pull request by jnicholCU**
Page type files for the newsletter

### CODE REVIEW

**Comment by jnicholCU** [comment]
Related Pull Request:

https://github.com/CuBoulder/ucb2021_base/pull/209
https://github.com/CuBoulder/ucb_custom_paragraphs/pull/23

**Review by patrickbrown-io — COMMENTED** [review]
Seems to be working on fresh install

**Review by patrickbrown-io — COMMENTED** [review]
Promos install correctly on fresh install

**Review by patrickbrown-io — APPROVED** [review]
Promo fields has image and link fields, all working correctly on fresh site install!

**Pull request merged**
